title: Daniel Alberto Martínez López
description: Developer Software
description: Programador Semi-Senior, con mucho gusto por la lectura, el arte, la cultura, los sitios de intereses teóricos e intelectuales, gaming of pokemon.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
